DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS users (
   id       BIGSERIAL PRIMARY KEY,
   name     VARCHAR(250) NOT NULL,
   email    VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
   id       BIGSERIAL PRIMARY KEY,
   name     VARCHAR(50) NOT NULL
);